apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-ms-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-ms-app
  template:
    metadata:
      labels:
        app: devops-ms-app
    spec:
      dnsPolicy: Default
      containers:
      - name: devops-ms-app
        image: amal26/devops-ms-app:latest
        ports:
        - containerPort: 3006